- name: Install required components
  apt: name={{ item }} state=present
  with_items:
    - sqlite3
    - libsqlite3-dev
    - ruby-dev
    - build-essential

- name: Install mailcatcher
  shell: gem install mailcatcher

- name: Set sendmail path
  lineinfile: dest=/etc/php5/apache2/conf.d/tweak.ini  regexp='^sendmail_path' line='sendmail_path = /usr/bin/env catchmail -f vagrant@example.local' backrefs=yes
