- name: PHP_codeSniffer
  shell: pear list -a PHP_CodeSniffer | grep PHP_CodeSniffer || pear install PHP_CodeSniffer
  ignore_errors: True
  
- name: Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

- name: Kint
  git: repo=git://github.com/raveren/kint.git dest=/usr/share/php/kint accept_hostkey=yes
