- name: Install postgis
  apt: name={{ item }} state=present
  with_items:
    - postgis
    - postgresql-9.3-postgis-2.1
    
- name: Import postgis.sql
  shell: sudo -upostgres psql -d{{ postgres_test_database }} --file=/usr/share/postgresql/9.3/contrib/postgis-2.1/postgis.sql
  
- name: Import spatial_ref_sys.sql
  shell: sudo -upostgres psql -d{{ postgres_test_database }} --file=/usr/share/postgresql/9.3/contrib/postgis-2.1/spatial_ref_sys.sql
  
- name: Alter geometry_columns
  shell: sudo -upostgres psql -d{{ postgres_test_database }} -c"ALTER TABLE geometry_columns OWNER TO {{ postgres_account_name }}";
  
- name: Alter spatial_ref_sys
  shell: sudo -upostgres psql -d{{ postgres_test_database }} -c"ALTER TABLE spatial_ref_sys OWNER TO {{ postgres_account_name }}";
