#! /bin/bash

DB_USER=root
DB_PASS={{ mysql_root_password }}
ACCOUNT_NAME={{ drupal_account_name }}
ACCOUNT_PASS={{ drupal_account_password }}

##############################

if [ -z $1 ]; then
  echo 'Site directory is required!'
  exit 1;
fi

echo 'Download drupal...';
echo ==========================
drush dl --drupal-project-rename=$1
cd $1

echo 'Start installation...';
echo ==========================
drush site-install standard --db-url=mysql://$DB_USER:$DB_PASS@localhost/$1 --site-name=$1 --account-mail=admin@localhost.my --account-name=$ACCOUNT_NAME --account-pass=$ACCOUNT_PASS -y
drush vset site_slogan 'Sandbox project'

echo 'Uninstall some modules...'
echo ==========================
drush dis toolbar contextual dashboard overlay rdf shortcut update search comment color -y
drush pm-uninstall toolbar contextual dashboard overlay rdf shortcut update search comment color -y

echo 'Install admin menu...'
echo ==========================
drush dl admin_menu -y
drush en admin_menu admin_menu_toolbar -y

echo 'Cleanup...'
echo ==========================
chmod -R 777 sites/default/files
drush cron
drush cc all
drush wd-del all -y
