- name: Install required components
  apt: name={{ item }} state=present
  with_items:
    - git
    - vim
    - curl
    - zip
    - unzip
    - mc
    - sqlite3
    - tree

- name: Install dot files
  copy: src={{ item }} dest=/home/vagrant/.{{ item }}
  with_items:
    - bashrc
    - gitconfig
    - vimrc
    - profile
    
- name: Creates mc directory
  file: path=/home/vagrant/.config/mc state=directory
    
- name: Install mc ini file
  copy: src=config/mc/ini dest=/home/vagrant/.config/mc/ini
  
- name: Copy locale
  copy: src=locale dest=/etc/default/locale
  
- name: Generate locale
  command: locale-gen en_US.UTF-8
  
- name: Set timezone.
  command: timedatectl set-timezone {{ server_timezone }}
