- name: Install required components
  apt: name={{ item }} state=installed
  with_items:
   - apache2
   - mysql-server
   - python-mysqldb
   - php5
   - php5-mysql
   - php5-curl
   - php5-intl
   - php5-mcrypt
   - php5-gd
   - php-apc
   - php-pear
   - php5-sqlite

- name: Enable mod rewrite
  command: a2enmod rewrite

- name: Remove index.html from document root
  file: path=/var/www/index.html state=absent

- name: Create phpinfo.php file
  shell: echo '<?php phpinfo();' > /var/www/phpinfo.php

- name: update mysql root password for all root accounts
  sudo: yes
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
      
- name: Replace default virual host
  template: src=000-default.conf dest=/etc/apache2/sites-available/000-default.conf owner=root group=root mode=0644
  
- name: Tweak apache settings.
  template: src=tweak.conf dest=/etc/apache2/conf-available/tweak.conf owner=root group=root mode=0644
       
- name: Sendmail script
  template: src=sendmail.php dest=/usr/share/php/sendmail.php owner=root group=root mode=0644
  
- name: Create mail directory
  file: path={{ mail_dir }} state=directory owner=root group=root mode=0777
  
- name: Tweak php settings
  copy: src=tweak.ini dest=/etc/php5/apache2/conf.d/tweak.ini owner=root group=root mode=644
  
- name: Create example virtual host
  copy: src=vhost_example.conf dest=/etc/apache2/sites-available/example.conf owner=root group=root mode=0644
  
- name: Create example directory
  file: path=/var/www/example state=directory
  
- name: Enable example site
  command: a2ensite example
  notify: restart apache

- name: Fixed missing php zlib functions
  copy: src=Tar.php dest=/usr/share/php/Archive/Tar.php owner=root group=root mode=0644

